### PR TITLE
Refactor avatar overlapping and masking

### LINKED ISSUE #25: Make focus-ring work with img property
Currently, `focus-ring` only works if avatar does not have image:

focus-ring

We need to fix that so it would work in all cases.

### LINKED ISSUE #26: Avatar overlapping and masking
From @jouni in the Slack discussion:

The current implementation still ends up with fractional pixels, and that results in the avatars “jiggling” when you resize the browser. Also, the mask image clips tightly around the avatar, making it impossible to use an outer box shadow for the focus ring.

From @yuriy-fix at https://github.com/vaadin/vaadin-avatar/pull/24#discussion_r448281033:

Problems with calculating margins as it's calculated based on number of items and the `+N` avatar is not a part of those.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #25 
Fixes #26

Implementation is based on https://github.com/vaadin/vaadin-avatar/issues/26#issuecomment-652430572

Note: this requires user to set width & height by changing `--vaadin-avatar-size` custom CSS property, which might be a bit inconvenient in terms of DX (setting `width` and `height` directly is not be picked up by `mask-position` calculation).

I had to update "scaled" visual tests accordingly, which illustrates the implications of this approach.

### CODE REVIEW

**Comment by web-padawan** [comment]
Tests for `avatar-group.html` are failing in IE11 with a `SyntaxError` ~and I have no idea what could cause it~ 😓 

**UPD**: obviously, it failed because of some CSS which apparently could not be parsed.

**Review by yuriy-fix — APPROVED** [review]
Seems to be good, the only thing:
Now when someone will try to adjust the sizes of the `vaadin-avatar` in the group like:
```
:host {
  height: 120px;
  width: 120px;
}
```
They will get into trouble:
Screen Shot 2020-07-06 at 13 53 19
So the only way to adjust the size is custom css variable usage 🤔

**Comment by web-padawan** [comment]
@yuriy-fix noted, thanks. The current approach also breaks IE11, so I'm going to refactor it.

**Comment by web-padawan** [comment]
Reverted the changes related to `--vaadin-avatar-size` CSS custom property because of IE11 issues.

Users overriding `width` and `height` for avatar group will now need to also set `mask-position`.

**Review by yuriy-fix — APPROVED** [review]

**Pull request merged**
