### PR TITLE
Accessibility improvements based on the feedback

### LINKED ISSUE #43: a11y: use role="button" for all avatars
From https://github.com/vaadin/vaadin-avatar/issues/10#issuecomment-656802750

> In my understanding it's more like a button / a group of buttons, especially if you are going to add a clicklistener or space-listener to it for interaction. (For example, to show more informations about the selected user in a dialog)

Currently, `role="image"` is used for avatars, except the `+N` avatar, which has `role="button"`. This is confusing.
We should consider using `role="button"` for all the avatars consistently.

### LINKED ISSUE #45: a11y: use aria-hidden="true" for SVG in the avatar
From https://github.com/vaadin/vaadin-avatar/issues/10#issuecomment-656802750

>  I would propose to add `aria-hidden="true"` to the `svg`s and `img` inside `<vaadin-avatar>` because not every screenreader is capable of handling shadow-dom properly.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #43 
Fixes #45 

These are the small fixes. I will submit another PR to handle `i18n` separately.

### CODE REVIEW

**Comment by web-padawan** [comment]
@knoobie would you like to test this PR and check if it looks good?

**Comment by knoobie** [comment]
Just from the source code: it looks good! 

it took me some time to get it working locally (total JS noob) - I followed your guide at https://github.com/vaadin/vaadin-avatar#running-demos-and-tests-in-a-browser. In the end to make it work, I had to install the polymer-cli locally instead of global. 

Looking at it with firefox accessibility tools looks good as well!

image

(the keyboard warning can be ignored; it's a false positive (you created the :focus styles - the tool can't find them) 

The only thing that bugs me is the empty text leaf next to the components. Is there some kind of forced whitespace somewhere?

**Comment by web-padawan** [comment]
I didn't try Firefox a11y tools yet. Will do.
My guess is that empty text node is whitespace, will try `strip-whitespace` attribute on the template.

**Comment by web-padawan** [comment]
Added `strip-whitespace` and now it no longer shows empty text leaf next to the components:

Screenshot 2020-07-14 at 14 59 42

**Comment by knoobie** [comment]
Perfect! Thanks for the effort!

**Comment by web-padawan** [comment]
This change has caused visual tests to fail, and the mask-image in the group looks incorrectly now.
So I had to remove that commit from this PR. Will ask the team to review it.

We don't use `strip-whitespace` anywhere else in components, and I don't think these leaf text nodes matter.
That's just how HTML works, and I believe that screen readers should be aware of it anyways.

**Comment by knoobie** [comment]
:lgtm:

**Review by DiegoCardoso — APPROVED** [review]
Tried with VoiceOver and Microsoft Narrator and it LGTM.

**Pull request merged**
